add_header X-FC-Ingress nginx always;
add_header X-FC-Probe-ID $fc_probe_id always;
add_header X-FC-Generation $fc_http_generation always;
add_header X-FC-Upstream-Status $upstream_status always;
add_header X-FC-Upstream-Connect $upstream_connect_time always;
add_header X-FC-Upstream-Header $upstream_header_time always;
add_header X-FC-Request-Limit $limit_req_status always;
add_header X-FC-Connection-Limit $limit_conn_status always;
