#!/bin/sh
set -e
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
fi
if command -v xdg-mime >/dev/null 2>&1; then
    xdg-mime default com.familyconnect.Client.desktop x-scheme-handler/familyconnect >/dev/null 2>&1 || true
fi
exit 0
